---
- hosts: all
  gather_facts: yes

  tasks:
  - name: obtain OS version
    debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}"

  - win_shell: C:\Users\frank.day\Desktop\Powershell\myfirst.ps1 >> C:\Users\frank.day\Desktop\Powershell\myfirst.log

  - win_shell: C:\Users\frank.day\Desktop\Powershell\sendmail-attachjpgfile.ps1

  - win_shell: echo %USERNAME%
    args:
     executable: cmd
    register: user_info

  - name: print OS version
    debug: var=user_info.stdout

  - name: run multi-lined shell commands
    win_shell: |
     $value = Test-Path -Path C:\ansibletemp
     if ($value) {
        Remove-Item -Path C:\ansibletemp -Force
     }
     New-Item -Path C:\ansibletemp -ItemType Directory
