---
- hosts: all
  gather_facts: yes

  tasks:
  - name: obtain OS version
    debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}"

  - win_shell: C:\Users\frank.day\Desktop\Powershell\myfirst.ps1 >> C:\Users\frank.day\Desktop\Powershell\myfirst.log

  - win_shell: C:\Users\frank.day\Desktop\Powershell\sendmail-attachjpgfile.ps1

  - win_shell: echo %USERNAME%
    args:
     executable: cmd
    register: user_info

  - name: print OS version
    debug: var=user_info.stdout

  - name: run multi-lined shell commands
    win_shell: |
     $value = Test-Path -Path C:\ansibletemp
     if ($value) {
        Remove-Item -Path C:\ansibletemp -Force
     }
     New-Item -Path C:\ansibletemp -ItemType Directory

  - name: Get disk facts
    win_disk_facts:

  - name: Output first disk size
    debug:
      var: ansible_facts.disks[0].size

  - name: Convert first system disk into various formats
    debug:
      msg: "{{ disksize_gib }}"
    vars:
      # Get first system disk        
      disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
      disksize_gib: "{{ (disk.size/1024|pow(3))|round|int }} GiB"
      disksize_gb:  "{{ (disk.size/1000|pow(3))|round|int }} GB"  # returns "240 GB" (value in GB)
      
  - name: Output disk serial number
    debug:
       var: ansible_facts.disks[0].serial_number
