---

- hosts: local_only_local_only

  tasks:

  - name: Just complete as valid YAML please
    command: date +%F
    register: result
    
  - name: print today's date
    debug: var=result.stdout
  
  - name: create an empty file
    file:
      path: /tmp/ansible.tmp.txt
      state: touch
